services:
  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: linkedin
      POSTGRES_PASSWORD: linkedin123
      POSTGRES_DB: core_service
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: ./core-service
      dockerfile: Dockerfile
    container_name: core_service_app
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/core_service
      SPRING_DATASOURCE_USERNAME: linkedin
      SPRING_DATASOURCE_PASSWORD: linkedin123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db

volumes:
  postgres_data: