server:
  port: ${SERVER_PORT:8081} # pega da variável de ambiente SERVER_PORT, padrão 8081

spring:
  neo4j:
    uri: bolt://neo4j:7687
    authentication:
      username: neo4j
      password: password

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: people-graph-group
      auto-offset-reset: earliest

jwt:
  secret: JY3nG8f9vZ1KxL6sQp2dRvM4tH5yZ7aB8cD9eF0gH1iJ2kL3
  expiration: 86400000            # expiração em ms (1h)