server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/core_service
    username: aaaa
    password: aaaa
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # Pode trocar para validate ou none em produção
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true       # Exibe as queries no console

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

jwt:
  secret: meuSegredoSuperSecreto123  # chave usada para assinar o token
  expiration: 3600000                # expiração em ms (1h)
