server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/meubanco
    username: joao
    password: senha123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # Pode trocar para validate ou none em produção
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true       # Exibe as queries no console

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: core-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

jwt:
  secret: meuSegredoSuperSecreto123  # chave usada para assinar o token
  expiration: 3600000                # expiração em ms (1h)
