server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/core_service
    username: aaaa
    password: aaaa
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # Pode trocar para validate ou none em produção
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true       # Exibe as queries no console

  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

jwt:
  secret: JY3nG8f9vZ1KxL6sQp2dRvM4tH5yZ7aB8cD9eF0gH1iJ2kL3
  expiration: 86400000            # expiração em ms (1h)
